In [67]:
import os
import sys
sys.path.append(os.path.realpath('../..'))
import aoc
my_aoc = aoc.AdventOfCode(2020,23)

In [68]:
input_text = "389125467"
from collections import deque

a = deque([1,2,3,4,5,6,7])
print(a)
idx = a.index(3) + 1
a.rotate(-1 * idx)
print(idx)
print(a)
b = []
for _ in range(3):
    cup = a.popleft()
    b.append(cup)
a.rotate(idx)
print(a)
print(a, b)


deque([1, 2, 3, 4, 5, 6, 7])
3
deque([4, 5, 6, 7, 1, 2, 3])
deque([1, 2, 3, 7])
deque([1, 2, 3, 7]) [4, 5, 6]


In [69]:
from collections import deque
from functools import lru_cache
import numpy as np

def move_cups_deque(cups, current_cup):
    cup_string = ''
    for cup in cups:
        if cup == current_cup:
            cup_string += f"({cup}) "
        else:
            cup_string += f"{cup} "
    # The crab picks up the three cups that are immediately clockwise of the current cup.
    # They are removed from the circle; cup spacing is adjusted as necessary to maintain the circle.
    idx = cups.index(current_cup) + 1
    cups.rotate(-1 * idx)
    pickup = []
    for _ in range(3):
        pickup.append(cups.popleft())
    cups.rotate(idx)    
    # destination: 2""")
    # The crab selects a destination cup: the cup with a label equal to the current cup's label minus one.
    # If this would select one of the cups that was just picked up, the crab will keep subtracting one
    # until it finds a cup that wasn't just picked up. 
    destination_cup = current_cup - 1
    while destination_cup in pickup:
        destination_cup -= 1
    # If at any point in this process the value goes below the lowest value on any cup's label,
    # it wraps around to the highest value on any cup's label instead.
    if destination_cup not in cups:
        destination_cup = max(cups)
    # The crab places the cups it just picked up so that they are immediately clockwise of the destination cup.
    # They keep the same order as when they were picked up.

    idx = cups.index(destination_cup) + 1
    cups.rotate(-1 * idx)
    cups.extend(pickup)
    cups.rotate(idx + 3)
    # The crab selects a new current cup: the cup which is immediately clockwise of the current cup.
    current_cup = cups[(cups.index(current_cup) + 1) % len(cups)]
    return current_cup
    
def move_cups_numpy(cups, current_cup, move):
    """Functions to move cups 1 turn"""
    # print(f"-- move {move} --")
    # cup_string = ''
    # for cup in cups:
    #     if cup == current_cup:
    #         cup_string += f"({cup}) "
    #     else:
    #         cup_string += f"{cup} "
    # print(f"cups: {cup_string}")
    # The crab picks up the three cups that are immediately clockwise of the current cup.
    # They are removed from the circle; cup spacing is adjusted as necessary to maintain the circle.
    idx = np.where(cups == current_cup)[0][0] + 1
    cups = np.roll(cups, -1 * idx)
    pickup = cups[:3]
    # print(f"pick up: {', '.join((str(num) for num in pickup))}")
    cups = cups[3:]
    cups = np.roll(cups, idx)
    # destination: 2""")
    # The crab selects a destination cup: the cup with a label equal to the current cup's label minus one.
    # If this would select one of the cups that was just picked up, the crab will keep subtracting one
    # until it finds a cup that wasn't just picked up. 
    destination_cup = current_cup - 1
    while destination_cup in pickup:
        destination_cup -= 1
    # If at any point in this process the value goes below the lowest value on any cup's label,
    # it wraps around to the highest value on any cup's label instead.
    if destination_cup not in cups:
        destination_cup = max(cups)
    # print(f"destination: {destination_cup}")
    # The crab places the cups it just picked up so that they are immediately clockwise of the destination cup.
    # They keep the same order as when they were picked up.
    idx = np.where(cups == destination_cup)[0][0] + 1
    cups = np.roll(cups, -1 * idx)
    cups = np.concatenate((cups, pickup))
    cups = np.roll(cups, idx + 3)
    # The crab selects a new current cup: the cup which is immediately clockwise of the current cup.
    idx = np.where(cups == current_cup)[0][0] + 1
    current_cup = cups[(idx) % len(cups)]
    return current_cup, cups
    
input_text = "389125467"
input_text = "467528193"
my_cups = np.array([int(num) for num in input_text])
current_cup = my_cups[0]
for move in range(1,101):
    current_cup, my_cups =  move_cups_numpy(my_cups, current_cup, move)
    # print()
idx = np.where(my_cups == 1)[0][0]
my_cups = np.roll(my_cups, -1 * idx)
print(''.join((str(cup) for cup in my_cups[1:].tolist())))


43769582


In [ ]:
input_text = "389125467"
# input_text = "467528193"
my_cups = np.array([int(num) for num in input_text])
my_cups = np.concatenate((my_cups, np.array(range(max(my_cups) + 1, 1000001))))
for num in  range(max(my_cups) + 1, 11):
    my_cups.append(num)
current_cup = my_cups[0]

seen = set()
for move in range(1,100000 + 1):
    my_tup = tuple(my_cups)
    if my_tup in seen:
        print(f"repeat at {move}")
    seen.add(my_tup)

    if move % 10000 == 0:
        print(move)
    current_cup, my_cups =  move_cups_numpy(my_cups, current_cup, move)
idx = np.where(my_cups == 1)[0][0]
print(f"1 is at {idx}")
nums = []
for pos in (1,2):
    idx_next = (idx + pos) % len(my_cups)
    num = my_cups[idx_next]
    nums.append(num)
    print(f"{num} is at {idx_next}")

print(np.prod(nums))


In [ ]:
import numpy as np

# Initial setup using a NumPy array
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a)  # [1 2 3 4 5 6 7]

# Find index of 3 and calculate the rotation offset
idx = np.where(a == 3)[0][0] + 1
a = np.roll(a, -idx)  # Equivalent to deque.rotate
print(idx)  # 4
print(a)  # [5 6 7 1 2 3 4]

# Extract first 3 elements
b = a[:3].tolist()
a = a[3:]  # Remaining elements after slicing

# Roll back the array to its original form
a = np.roll(a, idx)
print(a)  # [2 3 4 5]
print(a, b)  # [2 3 4 5] [5, 6, 7]


[1 2 3 4 5 6 7]
3
[4 5 6 7 1 2 3]
[1 2 3 7]
[1 2 3 7] [4, 5, 6]


In [ ]:
a = [1,2,3,4,5,6,7]
b = np.array(a)
print(b[0])

1


In [ ]:
3 in a

True

In [ ]:
len(a)

7

In [ ]:
a = (3,5)
np.prod(a)

15

In [28]:

def move_cups_linked_list(cups, moves):
    """Functions to move cups 1 turn"""
    first_cup = cups[0]
    max_cup = max(cups)
    linked_list = [0] * (max_cup + 1)  # Fixed-size list
    for idx in range(len(cups) - 1):
        linked_list[cups[idx]] = cups[idx + 1]
    linked_list[cups[-1]] = cups[0]  # Circular link
    current_cup = cups[0]
    for _ in range(moves):
        # print(f"-- move {move + 1} --")
        # cup_string = ''
        # cup = first_cup
        # for _ in range(len(cups)):
        #     if cup == current_cup:
        #         cup_string += f"({cup}) "
        #     else:
        #         cup_string += f"{cup} "
        #     cup = linked_list[cup]
        # print(f"cups: {cup_string}")
        # The crab picks up the three cups that are immediately clockwise of the current cup.
        # They are removed from the circle; cup spacing is adjusted as necessary to maintain the circle.
        pickup1 = linked_list[current_cup]
        pickup2 = linked_list[pickup1]
        pickup3 = linked_list[pickup2]
        pickup = {pickup1, pickup2, pickup3}
        # print(f"pick up: {', '.join((str(num) for num in pickup))}")
        
        # Close the gap
        linked_list[current_cup] = linked_list[pickup3]
        # The crab selects a destination cup: the cup with a label equal to the current cup's label minus one.
        # If this would select one of the cups that was just picked up, the crab will keep subtracting one
        # until it finds a cup that wasn't just picked up. 
        destination_cup = current_cup - 1
        while destination_cup in pickup:
            destination_cup -= 1
        # If at any point in this process the value goes below the lowest value on any cup's label,
        # it wraps around to the highest value on any cup's label instead.
        if destination_cup not in cups:
            destination_cup = max(cups)
            while destination_cup in pickup:
                destination_cup -= 1
        # print(f"destination: {destination_cup}")
        # The crab places the cups it just picked up so that they are immediately clockwise of the destination cup.
        # They keep the same order as when they were picked up.
        linked_list[pickup3] = linked_list[destination_cup]
        linked_list[destination_cup] = pickup1
        # The crab selects a new current cup: the cup which is immediately clockwise of the current cup.
        current_cup = linked_list[current_cup]
    return linked_list
    
input_text = "389125467"
# input_text = "467528193"
my_cups = [int(num) for num in input_text]
current_cup = my_cups[0]
moves = 100
linked_list = move_cups_linked_list(my_cups, moves)
cup = 1
cup_string = ''
for _ in range(len(my_cups)):
    cup_string += f"{cup}"
    cup = linked_list[cup]
print(f"cups: {cup_string.replace('1','')}")


cups: 67384529


In [30]:
import numpy as np

nums = np.array([489710, 540509], dtype=object)
product = np.prod(nums)
print(product)  # 264540672590
print(264692662390)


264692662390
264692662390
